var searchData=
[
  ['a_20c_2020_20tensor_20network_20library_0',['uni20 - A C++20 Tensor-Network Library',['../md_docs_2getting__started.html',1,'']]],
  ['ad_1',['Dataflow Reverse-Mode AD',['../md_docs_2async_2reverse__mode__ad.html',1,'']]],
  ['ad_3a_20ai_20guidance_2',['Uni20 Reverse-Mode AD: AI Guidance',['../md_docs_2ai__guidance_2reverse__mode__ad.html',1,'']]],
  ['adapted_20from_20expokit_3a_3',['The matrix exponential function was originally adapted from EXPOKIT:',['../md_src_2uni20_2expokit_2COPYRIGHT.html',1,'']]],
  ['ai_20assistants_4',['Uni20 Glossary for AI Assistants',['../md_docs_2ai__guidance_2glossary.html',1,'']]],
  ['ai_20guidance_5',['ai guidance',['../md_docs_2ai__guidance_2architecture__status.html',1,'Uni20 Architecture Status: AI Guidance'],['../md_docs_2ai__guidance_2async__runtime.html',1,'Uni20 Async Runtime: AI Guidance'],['../md_docs_2ai__guidance_2reverse__mode__ad.html',1,'Uni20 Reverse-Mode AD: AI Guidance']]],
  ['ai_20guidance_20for_20uni20_6',['AI Guidance for Uni20',['../md_docs_2ai__guidance_2README.html',1,'']]],
  ['and_20assignment_20semantics_7',['Async Storage and Assignment Semantics',['../md_docs_2async__storage.html',1,'']]],
  ['and_20awaiters_8',['Buffers and Awaiters',['../md_docs_2async_2buffers__and__awaiters.html',1,'']]],
  ['and_20cancellation_9',['Exceptions and Cancellation',['../md_docs_2async_2exceptions__and__cancellation.html',1,'']]],
  ['and_20roadmap_10',['Uni20 Architecture and Roadmap',['../md_docs_2roadmap.html',1,'']]],
  ['architecture_20and_20roadmap_11',['Uni20 Architecture and Roadmap',['../md_docs_2roadmap.html',1,'']]],
  ['architecture_20overview_12',['Uni20 Architecture Overview',['../md_docs_2architecture__diagram.html',1,'']]],
  ['architecture_20status_3a_20ai_20guidance_13',['Uni20 Architecture Status: AI Guidance',['../md_docs_2ai__guidance_2architecture__status.html',1,'']]],
  ['assignment_20semantics_14',['Async Storage and Assignment Semantics',['../md_docs_2async__storage.html',1,'']]],
  ['assistants_15',['Uni20 Glossary for AI Assistants',['../md_docs_2ai__guidance_2glossary.html',1,'']]],
  ['async_16',['C++ Coroutine Primer (For Uni20 Async)',['../md_docs_2async_2coroutines__primer.html',1,'']]],
  ['async_20cookbook_17',['Async Cookbook',['../md_docs_2async_2cookbook.html',1,'']]],
  ['async_20docs_18',['Audit of Existing Async Docs',['../md_docs_2async_2audit__legacy__docs.html',1,'']]],
  ['async_20documentation_19',['Async Documentation',['../md_docs_2async_2README.html',1,'']]],
  ['async_20getting_20started_20',['Async Getting Started',['../md_docs_2async_2getting__started.html',1,'']]],
  ['async_20quick_20reference_21',['Async Quick Reference',['../md_docs_2async_2quick__reference.html',1,'']]],
  ['async_20runtime_20model_22',['Async Runtime Model',['../md_docs_2async_2runtime__model.html',1,'']]],
  ['async_20runtime_3a_20ai_20guidance_23',['Uni20 Async Runtime: AI Guidance',['../md_docs_2ai__guidance_2async__runtime.html',1,'']]],
  ['async_20schedulers_24',['Async Schedulers',['../md_docs_2async_2schedulers.html',1,'']]],
  ['async_20storage_20and_20assignment_20semantics_25',['Async Storage and Assignment Semantics',['../md_docs_2async__storage.html',1,'']]],
  ['audit_20of_20existing_20async_20docs_26',['Audit of Existing Async Docs',['../md_docs_2async_2audit__legacy__docs.html',1,'']]],
  ['awaiters_27',['Buffers and Awaiters',['../md_docs_2async_2buffers__and__awaiters.html',1,'']]]
];
